- name: create "prometheus" group
  group:
    name: prometheus
    state: present

- name: create "prometheus" user
  user:
    name: prometheus
    shell: /bin/bash
    groups: prometheus
    append: yes

- name: Unarchive prometheus that needs to be downloaded
  unarchive:
    src: files/prometheus-2.25.2.linux-amd64.tar.gz
    dest: /usr/local/src
    owner: prometheus
    group: prometheus

- name: make directory /var/lib/prometheus
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Create prometheus symbolic link
  file:
    src: /usr/local/src/prometheus-2.25.2.linux-amd64/prometheus
    dest: /usr/local/prometheus
    state: link

- name: Remove prometheus.yml
  file:
    path: /usr/local/src/prometheus-2.25.2.linux-amd64/prometheus.yml
    state: absent

- name: Insert/Update prometheus.yml in /usr/local/src/prometheus-2.25.2.linux-amd64/
  blockinfile:
    path: /usr/local/src/prometheus-2.25.2.linux-amd64/prometheus.yml
    create: yes
    owner: prometheus
    group: prometheus
    mode: '0755'
    marker: ""
    block: |
        # my global config
        global:
            scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
            evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
        # scrape_timeout is set to the global default (10s).

        # Alertmanager configuration
        alerting:
            alertmanagers:
                - static_configs:
                    - targets:
                        # - alertmanager:9093

        # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
        rule_files:
            # - "first_rules.yml"
            # - "second_rules.yml"

        # A scrape configuration containing exactly one endpoint to scrape:
        scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets:
                - 192.168.56.100:9090

        - job_name: node_exporter
          static_configs:
            - targets:
                - 192.168.56.100:9100
                - 192.168.56.11:9100
                - 192.168.56.12:9100
                - 192.168.56.13:9100

        - job_name: pushgateway
          static_configs:
            - targets:
                - 192.168.56.100:9091

        - job_name: postgres_exporter
          static_configs:
            - targets:
              - 192.168.56.11:9187
              - 192.168.56.12:9187
              - 192.168.56.13:9187
      
- name: Remove prometheus.service
  file:
    path: /etc/systemd/system/prometheus.service
    state: absent

- name: Insert/Update prometheus.service in /etc/systemd/system/
  blockinfile:
    path: /etc/systemd/system/prometheus.service
    create: yes
    marker: ""
    mode: '0755'
    block: |
        [Unit]
        Description=Prometheus - Monitoring system and time series database
        Documentation=https://prometheus.io/docs/introduction/overview/

        [Service]
        Restart=always
        User=prometheus
        Type=simple
        ExecStart=/usr/local/src/prometheus-2.25.2.linux-amd64/prometheus \
        --config.file=/usr/local/src/prometheus-2.25.2.linux-amd64/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/data
        ExecReload=/bin/kill -HUP $MAINPID
        TimeoutStopSec=20s
        SendSIGKILL=no

        [Install]
        WantedBy=multi-user.target

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Systemctl enabled prometheus & systemctl start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

