- name: database cluster check
  shell: ls -l /db/pgdata/postgresql.conf
  register: result
  failed_when: result.rc not in [0, 1, 2]

- name: initdb
  shell: su - postgres -c initdb
  when: result.rc == 2

- name: Copy postgresql.conf
  copy:
    src: templates/postgresql.conf
    dest: /db/pgdata/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644
    backup: yes

- name: Copy pg_hba.conf
  copy:
    src: templates/pg_hba.conf
    dest: /db/pgdata/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0644
    backup: yes

- name: postgres process check
  shell: ps -ef | grep 'postgres:' | grep -v grep
  register: result_2
  failed_when: result_2.rc not in [0, 1]

- name: postgres start
  shell: su - postgres -c 'pg_ctl start'
  when: result_2.rc != 0

