- name: database cluster check
  shell: ls -l /db/pgdata/postgresql.conf
  register: result
  failed_when: result.rc not in [0, 1, 2]

- name: initdb
  shell: su - postgres -c initdb
  when: result.rc == 2

- name: postgres process check
  shell: ps -ef | grep 'postgres:'
  register: result
  failed_when: result.rc not in [0, 1]

- name: postgres start
  shell: su - postgres -c 'pg_ctl start'
  when: result.rc == 0

