- name: Ensure group "postgres" exists
  group:
    name: "{{ pg_group }}"
    state: present

- name: Add the user 'postgres' with a bash shell, appending the group 'postgres' to the user's groups
  user:
    name: "{{ pg_owner }}"
    shell: /bin/bash
    groups: "{{ pg_group }}"
    append: yes

- name: Unarchive prometheus that needs to be downloaded
  unarchive:
    src: https://ftp.postgresql.org/pub/source/v11.7/postgresql-11.7.tar.gz
    dest: /usr/local/src
    owner: "{{ pg_owner }}"
    group: "{{ pg_group }}"
    remote_src: yes

- name: Install a list of packages
  yum:
    name:
    - gcc
    - readline
    - readline-devel
    - zlib
    - zlib-devel
    state: present

- name: postgres install check
  shell: ls -l /usr/local/pgsql/bin
  register: result
  failed_when: result.rc not in [0, 1, 2]

- name: configure & make & make install
  shell: cd /usr/local/src/postgresql-11.7 && ./configure && make && make install
  when: result.rc == 2

- name: Make Directory for DB Cluster
  file:
    path: "{{ directory_pgdata }}"
    state: directory
    owner: "{{ pg_owner }}"
    group: "{{ pg_group }}"
    mode: '0755'    

- name: Insert/Update pushgateway.service in /etc/systemd/system/
  blockinfile:
    path: /home/postgres/.bash_profile
    create: yes
    marker: ""
    mode: '0644'
    block: |
        export PATH=/usr/local/pgsql/bin:$PATH
        export PGDATA=/db/pgdata

- name: initdb
  shell: su - postgres -c initdb
