#- name: manager 
#  hosts: manager
#  roles:
#    - mg_prometheus_install

- name: dbserver
  hosts: dbservers
  roles:
    - db_postgres_install
    - db_postgres_setting
    - db_node-exporter_install
    - db_postgres-exporter_install
