- name: synchronous_standby_names setting
  shell: su - postgres -c 'psql -c 'alter system set synchronous_standby_names = 'node2,node3'' ;

- name: postgres reload
  shell: su - postgres -c 'alter system set synchronous_standby_names = 'node2,node3' ;

