- name: synchronous_standby_names setting
  become: yes   
  become_method: su
  become_user: postgres
  shell: /usr/local/pgsql/bin/psql -c 'alter system set synchronous_standby_names = 'node2,node3'' ;

- name: postgres reload
  become: yes   
  become_method: su
  become_user: postgres
  shell: /usr/local/pgsql/bin/pg_ctl -D /db/pgdata reload
