- name: postgres process check
  shell: ps -ef | grep 'postgres:' | grep -v grep
  register: result_2
  failed_when: result_2.rc not in [0, 1]

- name: create slave database cluster
  become: yes   
  become_method: su
  become_user: postgres
  shell: /usr/local/pgsql/bin/pg_basebackup -h 192.168.56.11 -D /db/pgdata -R --progress -U postgres
  register: result
  failed_when: result.rc not in [0, 1, 2]
  when: result_2.rc != 0
  
- name: Copy recovery.conf
  copy:
    src: templates/recovery.conf.j2
    dest: /db/pgdata/recovery.conf
    owner: postgres
    group: postgres
    mode: 0644
    backup: yes
    when: result_2.rc != 0

- name: postgres start
  become: yes   
  become_method: su
  become_user: postgres
  shell: /usr/local/pgsql/pg_ctl start
  when: result_2.rc != 0
